// desweb/src/pages/Home.jsx
import { useEffect, useState } from "react";
import { getUsers, createUser, updateUser, deleteUser } from "../api/userService";
import UserForm from "../components/UserForm";
import UserList from "../components/UserList";

export default function Home() {
  const [users, setUsers] = useState([]);
  const [editingUser, setEditingUser] = useState(null);
  const [showForm, setShowForm] = useState(false);

  const loadUsers = async () => {
    const res = await getUsers();
    setUsers(res.data);
  };

  useEffect(() => {
    loadUsers();
  }, []);

  const handleSubmit = async (data) => {
    if (editingUser) {
      await updateUser(editingUser._id, data);
      setEditingUser(null);
    } else {
      await createUser(data);
    }
    setShowForm(false); 
    loadUsers();
  };

  const handleEdit = (user) => {
    setEditingUser(user);
    setShowForm(true);
  };

  const handleDelete = async (id) => {
    await deleteUser(id);
    loadUsers();
  };

  const closeForm = () => {
    setShowForm(false);
    setEditingUser(null);
  };

  return (
    <div style={{ padding: "20px" }}>
      <h1 style={{ textAlign: "center", marginBottom: "20px" }}>
        Formulario CRUD - React
      </h1>

      {}
      <button
        className="add-btn"
        onClick={() => setShowForm(true)}
      >
        Agregar Usuario
      </button>

      {}
      {showForm && (
        <div className="modal-overlay">
          <div className="modal-content">
            <UserForm onSubmit={handleSubmit} editingUser={editingUser} />
            <button className="close-btn" onClick={closeForm}>X</button>
          </div>
        </div>
      )}

      {/* Tabla */}
      <UserList users={users} onEdit={handleEdit} onDelete={handleDelete} />
    </div>
  );
}

// desweb-vue/src/views/Home.vue
<template>
  <div style="position: relative; padding: 20px;">
    <h1>CRUD - Vue</h1>

    <button @click="showForm = true" class="add-btn">
      Agregar Usuario
    </button>

    <div v-if="showForm" class="modal-overlay">
      <div class="modal-content">
        <UserForm
          :onSubmit="handleSubmit"
          :editingUser="editingUser"
        />
        <button class="close-btn" @click="closeForm">X</button>
      </div>
    </div>

    <UserList
      :users="users"
      @edit="handleEdit"
      @delete="handleDelete"
    />
  </div>
</template>

<script>
import { getUsers, createUser, updateUser, deleteUser } from "../api/userService";
import UserForm from "../components/UserForm.vue";
import UserList from "../components/UserList.vue";

export default {
  name: "Home",
  components: { UserForm, UserList },
  data() {
    return {
      users: [],
      editingUser: null,
      showForm: false,
    };
  },
  async mounted() {
    this.loadUsers();
  },
  methods: {
    async loadUsers() {
      const res = await getUsers();
      this.users = res.data;
    },
    async handleSubmit(data) {
      if (this.editingUser) {
        await updateUser(this.editingUser._id, data);
        this.editingUser = null;
      } else {
        await createUser(data);
      }
      this.showForm = false;
      this.loadUsers();
    },
    handleEdit(user) {
      this.editingUser = user;
      this.showForm = true;
    },
    async handleDelete(id) {
      await deleteUser(id);
      this.loadUsers();
    },
    closeForm() {
      this.showForm = false;
      this.editingUser = null;
    },
  },
};
</script>
